### ISSUE TITLE
Connector should use deepEqual

### ISSUE THREAD

**Issue by volkanunsal** [gaearon/react-redux#12]
I have been hunting a bug that turns out to have been caused by the fact that Connector shallowly compares the current slice to the next. The diffs buried deep in a slice doesn't trigger updates in the connected components because of this. For example:

Before:

```javascript
{
   MapReducer: {
      layers: []
   }
}
```

After:
```javascript
{
   MapReducer: {
      layers: [{id: 1, name: 'my-layer'}]
   }
}
```

...no updates. 

I know I can do `@connect(state => state.MapReducer)` but I also want the component to receive the state from other reducers. Any tips for me?

**Comment by gaearon** [comment]
Unless you're mutating inside your reducer (which you shouldn't do), your `MapReducer` object will be different every time, and `<Connector>` will work correctly. What's your `MapReducer` code like?

**Comment by volkanunsal** [comment]
> Unless you're mutating inside your reducer (which you shouldn't do), your MapReducer object will be different every time,

Hm... this may be the case. Here is what I'm doing:

```javascript
    case AT.MAP_TOGGLE_LAYERS:
      state.layers = state.layers
        .map( e => {
          if (e.enabled === undefined) { return e; }
          if(isSuperset(action.hidden)(e)){
            e.enabled = false;
          }
          // FIXME: why isn't this working?
          e.enabled = isSuperset(action.shown)(e);
          return e
      });
      return state;

```

**Comment by gaearon** [comment]
For example

```js
function (state, action) {
  state.xxx = yyy;
}
```

is wrong,

```js
// ES6
function (state, action) {
  return Object.assign({}, state, { xxx: yyy });
}

// ES7 spread syntax
function (state, action) {
  return { ...state, xxx: yyy );
}
```

is correct.

**Comment by volkanunsal** [comment]
Yup, that fixes it. I made a rookie mistake. :tired_face:

**Comment by gaearon** [comment]
No problem!
