### ISSUE TITLE
Q: Should ConnectorDecorator::shouldComponentUpdate consider changes in state slice?

### ISSUE THREAD

**Issue by dbrans** [gaearon/react-redux#22]
ConnectorDecorator::shouldComponentUpdate only looks at `this.props`. What if the result of `select(state, this.props)` has changed?
https://github.com/gaearon/react-redux/blob/52a280162c220d4ecf1ce826f9dcc423231e8c8b/src/components/createConnectDecorator.js#L13

**Comment by gaearon** [comment]
The changes to the state slice are currently handled by `<Connector>` it uses internally.
`<Connector>` is going away (see issue #1 and #16) so this will be more obvious soon.
