### ISSUE TITLE
About the LICENSE

### ISSUE THREAD

**Issue by gyzerok** [gaearon/react-redux#24]
Hi, Dan. I'm working around the project of connecting Redux and GraphQL. For now I'm feeling that it would be an alternative for react-redux. So I'm using some of your code in my project. There is no LICENSE in this repo, so I'm not sure if its ok. And how should I mention you in my repo? I'm just not competent with this license stuff.

**Comment by gaearon** [comment]
Sorry. It's MIT. I'll add the file & header.
