### ISSUE TITLE
Uncaught TypeError: this.unsubscribe is not a function

### ISSUE THREAD

**Issue by aaronjensen** [gaearon/react-redux#28]
Occasionally, when clicking through our app we get this:

![oliver 2015-08-07 11-01-56](https://cloud.githubusercontent.com/assets/8588/9142321/be9e7822-3cf3-11e5-8008-bf31d5a373bb.png)

Is it possible for will unmount to fire before mount? Should we check to ensure `unsubscribe` is there before calling it or is something else going on?

**Comment by aaronjensen** [comment]
I believe this has to do w/ some incorrect stuff that was happening in the app, though I don't know exactly what yet. This may be something that should never normally happen.

**Comment by aaronjensen** [comment]
Ok, so here's what we were doing... in `componentWillMount` we fired an action via `setTimeout` so that the `react-redux` subscription in `componentDidMount` will have already happened by the time the action is dispatched. It appears that this is a bad idea, though I do not understand why.

**Comment by gaearon** [comment]
OK I introduced this bug while tweaking @gnoff's code. :-(
Will push out a fix soon.

**Comment by gaearon** [comment]
Can you verify the bug is fixed in `0.5.1`?

**Comment by aaronjensen** [comment]
yep, it is. But then I get this: 

```
Uncaught Error: Invariant Violation: Component (with keys: getDOMNode,_handleChange,props,context,state,refs,_reactInternalInstance) contains `render` method but is not mounted in the DOM
```

which makes me think we're doing something very wrong. By removing the `setTimeout` in `componentWillMount` it works out.

What's the right way to fire an action when a component mounts? If the action immediately modifies state, `componentWillMount` is too soon, because react-redux doesn't subscribe until `componentDidMount`...

**Comment by gaearon** [comment]
>contains `render` method but is not mounted in the DOM

I found this: https://github.com/facebook/react/issues/4233.

Sounds like React throws if you use `findDOMNode(this)` when component is already unmounted. You should clear any previously set interval in `componentWillUnmount`.

>If the action immediately modifies state, componentWillMount is too soon, because react-redux doesn't subscribe until componentDidMount.

What do you mean by "too soon"? If React Redux doesn't update in some edge case, it's a bug, no matter where you call `dispatch`! You should file an issue, not just accept it like that. :smile:

**Comment by aaronjensen** [comment]
I just assume that you've thought of everything! I'll make sure it is what I think it is and file an issue when I get a sec. Thanks!

**Comment by gaearon** [comment]
Keeping it open for now so I don't forget about it.
I make mistakes all the time, you should help me figure them out!

**Comment by gaearon** [comment]
Ideally, the fastest way to figure out a solution is to discuss a failing test. Can I ask you to contribute it?

**Comment by aaronjensen** [comment]
Looks like you beat me to it! feel free to close #31, thanks. Btw, is there a reason to do it this way instead of by subscribing in `componentWillMount`?

**Comment by gaearon** [comment]
Yes, `componentWillMount` executes on server. This would cause memory leaks.

**Comment by aaronjensen** [comment]
The second error I saw is actually this: https://github.com/facebook/react/issues/2410

I'm not sure why yet, in my case, it has to do w/ clicking submit on a form triggering a router transition. I'll keep digging

**Comment by gaearon** [comment]
If you can reliably reproduce it on a small project let the folks know. It could be a React bug after all.

Are you by chance using React.addons.batchedUpdates or similar? Not saying I understand the issue but if so, try removing it and check if it makes the bug go away. I've heard about problems with batching and inputs although not sure what kind. Sorry if this is too vague. :-)

**Comment by aaronjensen** [comment]
We are, but removing it has no effect. I'll work on a small repro.

**Comment by aaronjensen** [comment]
You may be following that thread, so you may have seen it, but here's a repro: https://github.com/aaronjensen/react-2410-repro

The error does not happen if this line is removed: https://github.com/aaronjensen/react-2410-repro/blob/master/app/create_router.jsx#L10
