### ISSUE TITLE
Props not passed into connect selector

### ISSUE THREAD

**Issue by TimothyKrell** [gaearon/react-redux#30]
When this was part of the main redux repo, I could use props in my select functions, because they were passed in a second parameter.
```js
@connect((state, props) => {...}) // props is undefined
```
This was really useful to select state based on certain props that were passed in (I mostly used it for react router's params and such). It seems like the problem is right here, where only state is being passed: https://github.com/gaearon/react-redux/blob/master/src/components/createConnect.js#L91

**Comment by hartzis** [comment]
@TimothyKrell, it looks like in v0.5.0 you now have access to the components parent props via the third argument passed to connect

https://github.com/gaearon/react-redux/blob/master/README.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops

Example from readme:
##### Inject `todos` of a specific user depending on props, and inject `props.userId` into the action

```js
import * as actionCreators from './actionCreators';

function mapStateToProps(state) {
  return { todos: state.todos };
}

function mergeProps(stateProps, dispatchProps, parentProps) {
  return Object.assign({}, parentProps, {
    todos: stateProps.todos[parentProps.userId],
    addTodo: (text) => dispatchProps.addTodo(parentProps.userId, text)
  });
}

export default connect(mapStateToProps, actionCreators, mergeProps)(TodoApp);
```

**Comment by TimothyKrell** [comment]
Thanks! Should have read the README more carefully. Sorry for the noise!

**Comment by gaearon** [comment]
Yeah, this was done because once you want to something with state by props, you'll likely want to do something with actions too, but we can't rebind actions on every prop change (wasteful!) if you don't care about props. Hence the third argument.
