### ISSUE TITLE
state change doesn't cause re-render of connected component

### ISSUE THREAD

**Issue by bsr203** [gaearon/react-redux#37]
Hi,

I have the following behavior after upgrading to `0.5.0`

1. I changed the `@provide` to use `Provider`
2. didn't change connect for now
```
@connect(state => ({
 todos: state.todos
}))
```

Now, when component is mounted it calls the action to load the initial state

```
  componentDidMount() {
    this.props.actions.listTodos();
  }
```
component is rendered with default props

I could see the action causes the state to be populated 

```
API_TODOS_QUERY
  dispatching Object {type: "API_TODOS_QUERY", payload: Array[4]}
  next state Object {ui: Object, todos: Array[4]}
```

but there is no re-render. The new state is shown in the UI (rendered by the component) next time. that is if the same button/nav item is clicked again or navigate away and back to the same screen. 

Let me know what else needed to help me with this issue.

**Comment by gaearon** [comment]
This is a regression in 0.5.0. It should be fixed in [0.5.3](https://github.com/gaearon/react-redux/releases/tag/v0.5.3).
Better yet, upgrade to 0.6.0: https://github.com/gaearon/react-redux/releases/tag/v0.6.0

**Comment by gaearon** [comment]
Please reopen if you still have this issue after upgrading.

**Comment by bsr203** [comment]
It works .. great ...

**Comment by mjw56** [comment]
Seeing this issue as well, even after upgrading to ```0.6.0```.

app.ts:
```ts

// ...

let App = connect((state) => {
  return {
    books: state.books
  }
})(Component)

React.render(
  <Provider store={store} key="provider">
    {() => <App />}
  </Provider>,
 document.getElementById('app')
)
```

Component.ts:
```ts
interface Props { books: any; }
interface State { lists: any, date: any }

export class Component extends React.Component<Props, State> {

  constructor(props, context) {
    super(props, context);
    this.state = { lists: [], date: {} }
  }

  // ...
}
```

If I put a log statement inside ```connect()``` I do see that it is getting called with the latest state from the store.

Is extending ```React.Component``` and calling ```super``` causing issue? Interestingly, if I put a log inside the components ```render``` method, I do see the ```books``` object initially as ```undefined```, but never updated after that.
