### ISSUE TITLE
React Native support is broken

### ISSUE THREAD

**Issue by lwansbrough** [gaearon/react-redux#39]
https://github.com/gaearon/react-redux/blob/7458a923769e43dc647c270a7102d55236fa3b79/src/components/createConnect.js#L149

`process` is not available in React Native. React Native does however have a `__DEV__` global.

**Comment by gaearon** [comment]
Please let me know if `0.7.0` fixes it.

**Comment by lwansbrough** [comment]
Sorry this response is super late, but for anyone who may come across this issue: yes it fixes it! Thanks Dan.

**Comment by nkt** [comment]
React native 0.10.0 fixes this problem:
 > process.env.NODE_ENV: This value is defined to be "production" or "development" based on your current environment. Now you can use npm packages that rely on NODE_ENV!
https://github.com/facebook/react-native/releases/tag/v0.10.0-rc

**Comment by gaearon** [comment]
:+1:
