### ISSUE TITLE
Version 0.6.0 doesn't work with react-router

### ISSUE THREAD

**Issue by smashercosmo** [gaearon/react-redux#43]
I'm having rather strange issue in my app. After upgrading to 0.6.0 transitions to routes stoped working. While url in browser is changing the page stays the same. With 1.0.0-alpha everything works fine.

**Comment by gaearon** [comment]
It's a very vague description :-). Can you publish a reproducible example?

**Comment by smashercosmo** [comment]
@gaearon Ok) Here is an [example](https://github.com/smashercosmo/redux-react-router-issue)

**Comment by gaearon** [comment]
This is https://github.com/facebook/react/issues/2517 showing its head again.
The easy fix is to always pass `props` down when the router state changes.

Instead of:

```js
Router.run(routes, Router.HistoryLocation, (Handler) => {
  React.render(
    <Provider store={store}>
      {() => <Handler />}
    </Provider>, document.getElementById('root'));
});
```

write

```js
Router.run(routes, Router.HistoryLocation, (Handler, props) => { // note "props" here
  React.render(
    <Provider store={store}>
      {() => <Handler {...props} />} // note "props" here
    </Provider>, document.getElementById('root'));
});
```

We need to document this. I *think* this shouldn't affect React Router 1.0 but if you could verify this, it would be nice.

**Comment by gaearon** [comment]
Documented in https://github.com/gaearon/react-redux/commit/d4ae7b4d652d1ffc33145ad01f879ae85ba8b368.

**Comment by smashercosmo** [comment]
thx for the clarification)
