### ISSUE TITLE
Connector only checks state in shouldComponentUpdate

### ISSUE THREAD

**Issue by jptaylor** [gaearon/react-redux#45]
My connector looks like so:

```
function mapStateToProps(state) {
  const form = state.form;
  return {
    values: form.values,
    errors: form.errors,
    formErrors: form.formformErrors,
    sending: form.sending,
    complete: form.complete || false
  };
}

function mapDispatchToProps(dispatch) {
  return bindActionCreators(formActions, dispatch);
}
export default connect(
  mapStateToProps,
  mapDispatchToProps
)(SignUpForm);
```

Using the React inspector, I can see that the props of my components are updating when I interact with the form, but child components are not rendering. After debugging, the culprit appears to be with the connector's `shouldComponentUpdate` method:

```
Connect.prototype.shouldComponentUpdate = function shouldComponentUpdate(nextProps, nextState) {
     return !_utilsShallowEqual2['default'](this.state, nextState);
};
```

My state is immutable (and I have tried returning a random object from my reducers to test) and no matter what I can't seem to get this method to return true?

**Comment by gaearon** [comment]
Can you please make a minimal reproducible example?

**Comment by gaearon** [comment]
To clarify, 

```js
Connect.prototype.shouldComponentUpdate = function shouldComponentUpdate(nextProps, nextState) {
     return !_utilsShallowEqual2['default'](this.state, nextState);
};
```

is not a problem. The props you pass will end up in connector's state, so we can only compare state.

**Comment by jptaylor** [comment]
Issue was that my deep object were still being referenced, correct reducer needed to be:

```
case constants.FORM_FIELD_UPDATE:
      _.set(state.values, action.keyPath, action.value);
      _.set(state.errors, action.keyPath, action.errors);
      return {
        ...state,
        values: {...state.values},
        errors: {...state.errors}
      };
```

Apologies for false alarm.

**Comment by gaearon** [comment]
This is **not** a correct solution, it just works around the problem. Don't use `_.set` if want immutability :-). That's just asking for trouble.

You are still **mutating the `state` given to you**. This is wrong. It happens to work, but it negates many benefits of Redux (support for DevTools, record/replay, etc). **Do not do this.**

**Comment by gaearon** [comment]
Your proposed solution only works one level deep. If you subscribe to `state.form.values.something`, it will break again. Please don't use `_.set()`. It's not the tool for the job.

Consider using something like https://github.com/substantial/updeep or [Immutability Helpers](https://facebook.github.io/react/docs/update.html) instead of `_.set`. Otherwise you'll spend hours chasing weird bugs because `_.set` updated something deeply but there reference stayed the same.

**Comment by jptaylor** [comment]
Thank you @gaearon.

**Comment by dushyantsingh23** [comment]
Hey, can you look into this. My reducer is returning new state but the component is not being rendered.

http://stackoverflow.com/questions/39574376/component-not-able-to-re-render-when-state-is-changed
