### ISSUE TITLE
Best way to determine state depending on prop(s)? 

### ISSUE THREAD

**Issue by timbur** [gaearon/react-redux#56]
This is probably a stupid question, as I have a feeling I'm overlooking something obvious or doing something wrong.  :)

Suppose we have a tree of files to explore, and we want to be able to provide an initial state based on the files/directories the user had opened when they were last using the app or possibly based on the project/workspace/whatever.  So imagine we have this initial state serialized as follows:
```js
const open = {
  'redux/src': true,
  'redux/examples': true,
  'redux/examples/counter': true,
  'redux/examples/counter/server.js': true
};
```

And then for each item in the tree (let's call it a `Limb` component), we want to provide `props.isOpen` based on a combination of the `open` state and the `path` prop which is specific to each `Limb`.  And we also want to provide `toggle` prop (function) that updates both the `open` object and `props.isOpen` such that only the `Limb` being toggled is affected.

What's the best way to achieve this with `redux` and `react-redux`?

**Comment by gaearon** [comment]
Take a look at the last example in `connect` API reference. (Sorry, I'm on mobile :-)

**Comment by timbur** [comment]
Can you link me to what you're talking about when you get a chance?

**Comment by timbur** [comment]
Okay finally had a chance to actually look for it lol.  At the bottom of the main README right?  Above troubleshooting using `parentProps`?  I'll try this out now.

**Comment by timbur** [comment]
Whoa.  That was insanely easy.  Thanks a ton dude!!!!

**Comment by gaearon** [comment]
:+1:
