### ISSUE TITLE
ES6 Failed propType

### ISSUE THREAD

**Issue by badtant** [gaearon/react-redux#6]
Hi, I'm using the connector to a ES6 class. I get my data but a warning on the propType. "Warning: Failed propType: Required prop `data` was not specified in `Home`. Check the render method of `Router`."

I tried enabling es7.classProperties and move to static propTypes = ... That got rid of the warning but I rather stay on ES6 and only the ES7 features that i really want (like es7.decorators). Any ideas?

```javascript
@connect(state => ({
	data: state.info
}))
export default class Info extends React.Component {
	render() {
		return (
			<InfoComponent data={this.props.data}/>
		);
	}
}

Info.displayName = 'Info';
Info.propTypes = {
	data: React.PropTypes.object.isRequired
};
```

**Comment by danharper** [comment]
When you use the `@connect()` decorator, your `Info` class becomes immediately decorated with the `ConnectorDecorator` component.

When you then set `Info.propTypes`, you’re actually setting those prop types on the Connector, not on your Info component. So React is enforcing the props in the wrong place!

Instead, use an `InfoContainer`. I’d say this is a best practice in general, as it keeps your `Info` component as a “dumb component”, keeping the connected component separate. I do this even though I use static properties.

```js
class Info extends React.Component {
    render() {
        return (
            <InfoComponent data={this.props.data}/>
        );
    }
}

Info.displayName = 'Info';
Info.propTypes = {
    data: React.PropTypes.object.isRequired
};

@connect(state => ({
    data: state.info
}))
export default InfoContainer extends React.Component {
    render() {
        return (
            <Info {...this.props} />
        )
    }
}
```

Or, you could probably do this (which is less extensible)

```js
@connect(state => ({
    data: state.info
}))
export default InfoContainer extends Info {}
```

**Comment by gaearon** [comment]
Don't use inheritance please :-). I have never seen a justifiable case for it in React.
I think the easiest way out is just not to use decorators in this case.

```js
class Info extends React.Component {
    render() {
        return (
            <InfoComponent data={this.props.data}/>
        );
    }
}

Info.displayName = 'Info';
Info.propTypes = {
    data: React.PropTypes.object.isRequired
};

export default connect(state => ({
    data: state.info
}))(Info)
```

**Comment by blesswinsamuel** [comment]
Another method:

```
@connect(state => ({
    data: state.info
}))
export default class Info extends React.Component {
    static propTypes = {
        data: React.PropTypes.object.isRequired
    }

    render() {
        return (
            <InfoComponent data={this.props.data}/>
        );
    }
}
```

**Comment by joshmanderson** [comment]
@badtant A fix I just discovered, which allows you to use the decorator:
```javascript
@connect(state => ({
    data: state.info
}))
class Info extends React.Component {
    render() {
        return (
            <InfoComponent data={this.props.data}/>
        );
    }
}

Info.displayName = 'Info';
Info.WrappedComponent.propTypes = {
    data: React.PropTypes.object.isRequired
};

export default Info;
```
Note the use of the static property `WrappedComponent`, which is "The original component class passed to connect()", and can be found in the documentation here: https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options

**Comment by joshmanderson** [comment]
@blesswinsamuel In regards to your code using static propTypes...
Does that work for you? Using static propTypes as you have done there still gives me the same warning messages...

**Comment by jordanpapaleo** [comment]
@joshmanderson Nice catch!
