### ISSUE TITLE
null as the selector parameter to connect

### ISSUE THREAD

**Issue by quirinpa** [gaearon/react-redux#63]
Some components want to fire actions only and need not be connected to store state, i propose that connect accepts null as a first parameter ( default to () => ({}) ), it's not THAT important :P

**Comment by gnoff** [comment]
I'm pretty sure the documentation already mentions this but that is exactly how connect already works.

**Comment by quirinpa** [comment]
Oh. You're right. I don't know why it wasn't working for me. Sorry :P

**Comment by gnoff** [comment]
No problem. Can you confirm it works now?

**Comment by quirinpa** [comment]
Yes it does work fine :) thanks gnoff

**Comment by gnoff** [comment]
Cool
