### ISSUE TITLE
How to integrate with react-router v0.13.3?

### ISSUE THREAD

**Issue by volkanunsal** [gaearon/react-redux#7]
So I've been having the hardest time integrating this with React Router. Does anyone have any tips on this? Here is how I am trying to initialize the router now, and it seems to lose the context in the children of the Page component:

```js
Router.run(routes, Router.HistoryLocation, (Handler, state) => {
    React.render(<Provider store={store}>{() => { 
         return <Handler {...state} /> 
    }}</Provider>, document.getElementById('App'));
  });
```

And here is the warning I get:

```
Warning: Failed Context Types: Required context `store` was not specified in `Connector`.
```

**Comment by gaearon** [comment]
I just checked and it works fine for me.
My best bet is you have duplicate Reacts so they don't recognize each other's context.

Make sure you don't have

```
node_modules/react-router/node_modules/react
node_modules/react-redux/node_modules/react
etc
```

and only have `node_modules/react`.

**Comment by rob-mccann** [comment]
My limited understanding is that react-router is the parent for your page components rather than the app wrapper.

We're using a newer version of react router and hit a similar thing with react-intl but this should still apply:

1) We extend the router class to put the objects from props onto the context
```javascript
import React  from 'react';
import Router from 'react-router';

export default class extends Router {
    getChildContext() {
        const context = this.context,
              props   = this.props;

        return {
            locales: props.locales || context.locales,
            formats: props.formats || context.formats,
            messages: props.messages || context.messages,

            config: props.config || context.config,

            router: this
        };
    }

    static childContextTypes = {
        locales: React.PropTypes.oneOfType([
            React.PropTypes.string,
            React.PropTypes.array
        ]),

        formats: React.PropTypes.object,
        messages: React.PropTypes.object,

        config: React.PropTypes.object.isRequired,

        router: React.PropTypes.object.isRequired
    }
}
```

**Comment by volkanunsal** [comment]
I think this was a duplicate Reacts issue. Thanks for the help! :+1:
