### ISSUE TITLE
Possible to use @connect functionality without wrapping it in a new component?

### ISSUE THREAD

**Issue by dax0** [gaearon/react-redux#8]
This isn't a common use case but the connect decorator breaks the case when a parent component needs to call a child component's functions as documented here: https://facebook.github.io/react/tips/expose-component-functions.html

I agree it's better to handle these situations using flux or props but was curious to see whether or not this incompatibility can be avoided.

**Comment by gaearon** [comment]
We've decided to expose a way to access the instance (via a `getUnderlyingRef()` method). This will be in our API revamp from #16.
