### ISSUE TITLE
Clean before building

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-redux#9]
Seems like there's an extra file in `dist` right now because we don't clean before build.

**Comment by mikekidder** [comment]
I can switch react-redux to use npm tasks like redux, if you like. 
That will take of this extra build as well.

**Comment by gaearon** [comment]
Yes, this would be appreciated.

**Comment by mikekidder** [comment]
PR #19 is ready for review...

**Comment by gaearon** [comment]
Fixed by #19.
